"""add_updated_at_to_context_blocks

Revision ID: 1ed6704aac6e
Revises: fff6a99f033a
Create Date: 2026-06-14 16:43:52.473873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed6704aac6e'
down_revision: Union[str, Sequence[str], None] = 'fff6a99f033a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first (SQLite limitation), then backfill, then set NOT NULL via server_default
    op.add_column('context_blocks', sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        nullable=True,
        server_default=sa.func.now(),
    ))
    # Backfill existing rows using created_at
    op.execute("UPDATE context_blocks SET updated_at = created_at WHERE updated_at IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_blocks', 'updated_at')
    # ### end Alembic commands ###
