"""devmemory inject — Auto-load DevMemory context into AI tool files.

Cross-platform Python replacement for the bash devmemory-inject script.
Works on Windows, macOS, and Linux.

Usage::

    devmemory inject                          # inject for current directory
    devmemory inject --cwd /path/to/project   # explicit project path
    devmemory inject --tool claude            # target-specific preamble

What it does:
    1. Fetches the latest session context from the DevMemory REST API
    2. Writes it to tool-specific files that are auto-read on session start:
       - CLAUDE.md              (Claude Code reads this automatically)
       - .augment/rules/devmemory.md  (Augment reads rules/ on startup)
    3. Optionally adds CLAUDE.md to .gitignore
    4. Prints a summary
    5. Never fails with non-zero exit — safe for hooks
"""

from __future__ import annotations

import json
import os
import sys
import urllib.parse
import urllib.request
from pathlib import Path

from devmemory.cli.install import load_api_key


def _fetch_resume(
    cwd: str,
    api_key: str,
    host: str = "http://localhost:8765",
    target_tool: str = "generic",
) -> dict | None:
    """Call GET /context/resume and return parsed JSON, or None on failure."""
    encoded_cwd = urllib.parse.quote(cwd, safe="")
    url = f"{host}/context/resume?cwd={encoded_cwd}&target_tool={target_tool}"

    req = urllib.request.Request(url, headers={"X-API-Key": api_key})

    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception:
        return None


def _write_claude_md(cwd: str, prompt: str) -> Path:
    """Write context to CLAUDE.md in the project root."""
    path = Path(cwd) / "CLAUDE.md"
    content = f"<!-- Auto-generated by devmemory inject. Do not edit manually. -->\n{prompt}\n"
    path.write_text(content, encoding="utf-8")
    return path


def _write_augment_rules(cwd: str, prompt: str) -> Path | None:
    """Write context to .augment/rules/devmemory.md if .augment/ exists or tool is augment."""
    augment_dir = Path(cwd) / ".augment"
    rules_dir = augment_dir / "rules"

    # Only write if .augment/ already exists (user has Augment configured for this project)
    if not augment_dir.exists():
        return None

    rules_dir.mkdir(parents=True, exist_ok=True)
    path = rules_dir / "devmemory.md"
    content = f"<!-- Auto-generated by devmemory inject. Do not edit manually. -->\n{prompt}\n"
    path.write_text(content, encoding="utf-8")
    return path


def _write_cursor_rules(cwd: str, prompt: str) -> Path | None:
    """Write context to .cursor/rules/devmemory.mdc if .cursor/ exists in the project.

    Uses Cursor's MDC frontmatter with ``alwaysApply: true`` so Cursor automatically
    loads the context into every chat without the user needing to @-mention it.
    """
    cursor_dir = Path(cwd) / ".cursor"
    if not cursor_dir.exists():
        return None

    rules_dir = cursor_dir / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    path = rules_dir / "devmemory.mdc"
    content = (
        "---\n"
        "description: DevMemory session context — auto-generated, do not edit manually.\n"
        "alwaysApply: true\n"
        "---\n"
        f"{prompt}\n"
    )
    path.write_text(content, encoding="utf-8")
    return path


def _write_windsurf_rules(cwd: str, prompt: str) -> Path | None:
    """Write context to .windsurfrules in the project root if Windsurf is configured.

    Windsurf reads ``.windsurfrules`` automatically on every session, making this
    the equivalent of a SessionStart hook for Windsurf projects.
    """
    windsurf_dir = Path(cwd) / ".windsurf"
    windsurfrules_path = Path(cwd) / ".windsurfrules"

    # Only write if .windsurf/ dir exists OR .windsurfrules already present
    if not windsurf_dir.exists() and not windsurfrules_path.exists():
        return None

    content = f"<!-- Auto-generated by devmemory inject. Do not edit manually. -->\n{prompt}\n"
    windsurfrules_path.write_text(content, encoding="utf-8")
    return windsurfrules_path


def _ensure_gitignore(cwd: str) -> None:
    """Add all devmemory-injected files to .gitignore if not already present."""
    gitignore_path = Path(cwd) / ".gitignore"

    entries_to_add = [
        "CLAUDE.md",
        ".augment/rules/devmemory.md",
        ".cursor/rules/devmemory.mdc",
        ".windsurfrules",
    ]

    existing = ""
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")

    additions = []
    for entry in entries_to_add:
        if entry not in existing:
            additions.append(entry)

    if additions:
        separator = "\n" if existing and not existing.endswith("\n") else ""
        block = f"{separator}\n# DevMemory auto-generated context (do not commit)\n"
        block += "\n".join(additions) + "\n"
        gitignore_path.write_text(existing + block, encoding="utf-8")


def run_inject(args) -> None:
    """Handle the 'devmemory inject' subcommand."""
    cwd = getattr(args, "cwd", None) or os.getcwd()
    tool = getattr(args, "tool", "generic") or "generic"
    host = getattr(args, "host", None) or os.environ.get("DEVMEMORY_HOST", "http://localhost:8765")

    api_key = getattr(args, "api_key", None) or load_api_key()
    if not api_key:
        # Silent failure — don't break tool startup
        print("ℹ️  devmemory inject: No API key found. Skipping.", file=sys.stderr)
        sys.exit(0)

    data = _fetch_resume(cwd, api_key, host=host, target_tool=tool)
    if data is None:
        print(f"⚠️  devmemory inject: Could not reach DevMemory at {host}", file=sys.stderr)
        print("   Start it with: devmemory --rest", file=sys.stderr)
        sys.exit(0)

    has_context = data.get("has_context", False)
    if not has_context:
        msg = data.get("message", "No context available.")
        print(f"ℹ️  devmemory inject: {msg}")
        sys.exit(0)

    prompt = data["prompt"]
    project = data.get("project", "unknown")
    session_title = data.get("session_title", "")
    block_count = data.get("block_count", 0)

    # Write to tool-specific files
    written_to = []

    claude_path = _write_claude_md(cwd, prompt)
    written_to.append(str(claude_path))

    augment_path = _write_augment_rules(cwd, prompt)
    if augment_path:
        written_to.append(str(augment_path))

    cursor_path = _write_cursor_rules(cwd, prompt)
    if cursor_path:
        written_to.append(str(cursor_path))

    windsurf_path = _write_windsurf_rules(cwd, prompt)
    if windsurf_path:
        written_to.append(str(windsurf_path))

    # Ensure auto-generated files are in .gitignore
    _ensure_gitignore(cwd)

    # Summary
    print(
        f"✅ devmemory inject: Loaded context for '{project}' — "
        f"'{session_title}' ({block_count} blocks)"
    )
    for p in written_to:
        print(f"   Written to: {p}")
