// `devmemory inject` — fetch the latest resume prompt for the project in `cwd`
// and write it to CLAUDE.md. Project resolution is client-side (works against a
// hosted backend), then we resume the latest active session by id.

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { apiCall } from "./api.js";
import { resolveProject } from "./git.js";

export async function runInject({ cwd, tool, apiKey }) {
  const dir = cwd || process.cwd();
  const project = resolveProject(dir);

  const sessions = await apiCall("GET", "/sessions", {
    apiKey,
    params: { project_slug: project.slug, status: "active", limit: 1 },
  });
  if (sessions.ok === false) {
    console.error(`ℹ️  devmemory inject: ${sessions.error}`);
    return;
  }
  const list = sessions.sessions || [];
  if (list.length === 0) {
    console.log(`ℹ️  devmemory inject: no active session for '${project.name}'. Start one first.`);
    return;
  }

  const resume = await apiCall("GET", `/sessions/${encodeURIComponent(list[0].id)}/resume`, {
    apiKey,
    params: { target_tool: tool || "generic" },
  });
  if (resume.ok === false || !resume.prompt) {
    console.error(`ℹ️  devmemory inject: ${resume.error || "no context to inject yet"}`);
    return;
  }

  const path = join(dir, "CLAUDE.md");
  writeFileSync(
    path,
    `<!-- Auto-generated by devmemory inject. Do not edit manually. -->\n${resume.prompt}\n`,
    "utf8",
  );
  console.log(`✅ devmemory inject: wrote context for '${project.name}' → ${path}`);
}
